Bootstrap: docker
From: debian:buster

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 2.5.1

%post
    apt-get update
    apt-get install -y --no-install-recommends apt-utils bzip2 build-essential
    apt-get update --fix-missing

####################################################################################
%appinstall bamtools
    apt-get install -y wget
    wget https://github.com/pezmaster31/bamtools/archive/v2.5.1.tar.gz
    tar -xjvf v2.5.1.tar.gz && v2.5.1.tar.gz
    mkdir /opt/bamtools
    cd bamtools-2.5.1 && mkdir build && cd build
    cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/bamtools -DASSIMP_BIN_INSTALL_DIR=$(pwd) ..
    
%apphelp bamtools
    /opt/bamtools/bamtools --help

%apprun samtools
    /opt/bamtools/bamtools "$@"
