Bootstrap: docker
From: quay.io/biocontainers/bamtools:2.5.1--he513fc3_6

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/icaoberg/singularity-bamtools
    VERSION 2.5.1

%post
   rm /etc/resolv.conf

####################################################################################
